name: fruit_esc
description: ESC command
version: 0.1.4
repository: https://github.com/prtmax/psdk-examples
environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  psdk_frame_father: ^0.1.4
  psdk_device_adapter: ^0.1.4
  psdk_imageb: ^0.1.4


dev_dependencies:
  lints: ^5.1.1
  test: ^1.28.0
